#pragma once

void creatingTest();
void copyingTest();
void movingTest();
void cloningTest();
void gettingDataTest();
void settingDataTest();
void gettingCordTest();
void settingCordTest();
void scaleTest();
void gettingDimTest();
void incTest();
void decTest();
void addTest();
void subTest();
void dotTest();
void equalsTest();
void normTest();
void applyingTest();
void foreachTest();
void vectorTests();
